name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions-J1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

  Explore-GitHub-Actions-J2:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "test"


  Explore-GitHub-Actions-Run-Bash-Scripts:
    runs-on: ubuntu-latest
    steps:
      - name: ttt
        run: bash ${GITHUB_WORKSPACE}/.github/script.sh
